version: 2.1

orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@3.1.1
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - restore_cache:
        keys:
          - fs-dependencies-{{checksum "udagram-api/package.json"}}-{{checksum "udagram-frontend/package.json"}}
          - fs-dependencies

      - run:
        name: install frontend
        command: npm run frontend:install
      - run:
        name: install backend
        command: npm run backend:install
      - save_cache:
        paths:
          - udagram-api/node_modules
          - udagram-frontend/node_modules
        key: fs-dependencies-{{checksum "udagram-api/package.json"}}-{{checksum "udagram-frontend/package.json"}}
      - run:
        name: build frontend
        command: npm run frontend:build
      - run:
        name: build backend
        command: npm run backend:build
      - run:
        name: deploy backend
        command: npm run backend:deploy
      - run:
        name: deploy frontend
        command: npm run frontend:deploy

workflows:
  build_and_deploy:
    jobs: -build
